[build]
  base = "nextjs-setup/nextjs-dashboard"
  command = "pnpm --filter nextjs-dashboard... run build"
  publish = "nextjs-setup/nextjs-dashboard/.next"

[build.environment]
  SECRETS_SCAN_OMIT_PATHS = "**/*.md,**/*.mdx,**/.env.example,**/README.md,**/.netlify/**"
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_APP_URL,REDIS_URL,DRY_RUN"